"""
API-in-the-loop REINFORCE trainer.

Every single action in every episode is generated by your configured LLM.
No templates, no heuristics, no fallbacks. If the LLM is not configured the
script exits immediately with a clear error — there is no fake work to fall
back to.

What is trained:
  A contextual bandit (the same OnlineRLPolicy used by the server) that learns
  which OBJECTIVE prompt to give the LLM at the start of each episode. It does
  NOT modify the LLM's weights — those live on the provider's servers. It learns
  which framing (schema exploration, OCR focus, shell tracing, etc.) produces
  higher rewards from the LLM.

  Trained weights are saved to assets/bandit_weights.json and loaded
  automatically when the server starts, so the server's arm-selection policy
  benefits from offline training.

Usage:
    # Start the server first
    .venv/Scripts/uvicorn fraud_hunter_env.server.app:app --port 8000

    # Then run training (reads .env automatically)
    python training/train_api.py
    python training/train_api.py --episodes 100 --max-steps 30
"""

from __future__ import annotations

import argparse
import json
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

# ── repo root + .env ──────────────────────────────────────────────────────────
_REPO_ROOT = Path(__file__).resolve().parent.parent
try:
    from dotenv import load_dotenv
    load_dotenv(_REPO_ROOT / ".env", override=False)
except ImportError:
    pass

sys.path.insert(0, str(_REPO_ROOT))

from fraud_hunter_env.server.online_rl import OnlineRLPolicy  # noqa: E402

_WEIGHTS_PATH = _REPO_ROOT / "assets" / "bandit_weights.json"
_LOG_PATH     = _REPO_ROOT / "assets" / "train_api_log.jsonl"

# Objectives passed to the LLM via agent_action.
# The bandit learns which one leads to higher rewards for a given observation.
_OBJECTIVES: dict[str, str] = {
    "llm": (
        "You are a fraud investigator. Explore the case database, "
        "identify shell companies and billing anomalies, then submit the case."
    ),
    "sql_schema": (
        "Start by running sql_query or code_act to list all tables and row counts. "
        "Then query the most suspicious tables before submitting."
    ),
    "ocr_doc": (
        "Find a scanned PDF in the scanned_claims directory using ocr_document. "
        "Compare the extracted fields against the database claim record, then submit."
    ),
    "code_list_comms": (
        "Use code_act to list files in intercepted_comms. "
        "Read them and identify entity names, then link shell companies before submitting."
    ),
}


# ── HTTP helpers ──────────────────────────────────────────────────────────────

def _post(url: str, body: dict, timeout: int = 45) -> dict:
    data = json.dumps(body).encode()
    req = urllib.request.Request(
        url, data=data, headers={"Content-Type": "application/json"}
    )
    with urllib.request.urlopen(req, timeout=timeout) as r:
        return json.loads(r.read())


def _get(url: str, timeout: int = 5) -> dict:
    with urllib.request.urlopen(url, timeout=timeout) as r:
        return json.loads(r.read())


def _check_server_and_llm(base_url: str) -> None:
    """Exit loudly if the server is down or LLM is not configured."""
    # server health
    try:
        _get(f"{base_url}/health", timeout=3)
    except Exception:
        sys.exit(
            f"\nServer not reachable at {base_url}.\n"
            f"Start it with:\n"
            f"  .venv/Scripts/uvicorn fraud_hunter_env.server.app:app --port 8000\n"
        )

    # LLM configured?
    try:
        health = _get(f"{base_url}/fraud_hunter/health")
    except Exception:
        health = {}

    if not health.get("agent_enabled", False):
        sys.exit(
            "\nLLM not configured — agent_enabled=false.\n"
            "Set these in your .env file:\n"
            "  FRAUD_HUNTER_LLM_BASE_URL=https://api.groq.com/openai/v1\n"
            "  FRAUD_HUNTER_LLM_MODEL=llama-3.1-8b-instant\n"
            "  FRAUD_HUNTER_LLM_API_KEY=<your key>\n"
            "\nThere is no fallback — training requires a real LLM.\n"
        )


# ── Episode ───────────────────────────────────────────────────────────────────

def run_episode(base_url: str, objective: str, max_steps: int) -> float:
    """
    Run one full episode. Every action is LLM-generated via /fraud_hunter/agent_action.
    Returns the cumulative episode reward.
    """
    reset_resp  = _post(f"{base_url}/reset", {})
    observation = reset_resp.get("observation", {})
    done        = reset_resp.get("done", False)
    total       = float(reset_resp.get("reward", 0.0))

    for _ in range(max_steps):
        if done:
            break

        # LLM generates the action — no template fallback
        try:
            agent_resp = _post(
                f"{base_url}/fraud_hunter/agent_action",
                {"observation": observation, "objective": objective},
                timeout=60,
            )
        except urllib.error.HTTPError as exc:
            body = exc.read().decode(errors="replace") if exc.fp else str(exc)
            raise RuntimeError(
                f"agent_action returned HTTP {exc.code}: {body[:200]}\n"
                "Check that your LLM API key and base URL are correct."
            ) from exc

        action = agent_resp.get("action")
        if not action:
            raise RuntimeError(f"agent_action returned no action: {agent_resp}")

        step_resp   = _post(f"{base_url}/step", {"action": action})
        observation = step_resp.get("observation", {})
        total      += float(step_resp.get("reward", 0.0))
        done        = step_resp.get("done", False)

    return total


# ── Training loop ─────────────────────────────────────────────────────────────

def train(base_url: str, episodes: int, max_steps: int) -> None:
    _check_server_and_llm(base_url)

    # Load pre-trained weights if they exist, otherwise start fresh.
    policy = OnlineRLPolicy(weights_path=_WEIGHTS_PATH)
    if _WEIGHTS_PATH.exists():
        print(f"Loaded bandit weights from {_WEIGHTS_PATH} ({policy._updates} prior updates)")
    else:
        print("No prior weights found — starting from scratch.")

    _LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
    log_fh = _LOG_PATH.open("a", encoding="utf-8")

    print(f"\nAPI-in-the-loop REINFORCE: {episodes} episodes, max {max_steps} steps/ep")
    print(f"Log → {_LOG_PATH}\n")
    print(f"{'ep':>4}  {'arm':<18}  {'reward':>8}  {'baseline':>8}  arm probabilities")
    print("─" * 80)

    for ep in range(1, episodes + 1):
        # Bandit picks which objective to pass to the LLM.
        # allow_llm=True so the "llm" arm (generic objective) is in play.
        obs_stub: dict = {}
        decision  = policy.choose_arm(obs_stub, "", allow_llm=True)
        token     = decision["token"]
        arm       = decision["arm"]
        objective = _OBJECTIVES.get(arm, _OBJECTIVES["llm"])

        t0 = time.monotonic()
        try:
            reward = run_episode(base_url, objective, max_steps)
        except Exception as exc:
            print(f"\n  ep {ep} FAILED: {exc}")
            policy.update(token, -1.0)
            continue

        result   = policy.update(token, reward)
        elapsed  = time.monotonic() - t0
        snap     = policy.snapshot()
        probs    = snap.get("weights", {})  # raw weights, not softmax — use snapshot probs
        probs_str = "  ".join(
            f"{a}={p:.3f}"
            for a, p in decision["probs"].items()
        )
        print(
            f"{ep:>4}  {arm:<18}  {reward:>+8.2f}  "
            f"{result['baseline']:>+8.2f}  {probs_str}  ({elapsed:.1f}s)"
        )

        log_fh.write(json.dumps({
            "episode": ep,
            "arm": arm,
            "reward": reward,
            "baseline": result["baseline"],
            "advantage": result["advantage"],
            "probs": decision["probs"],
            "elapsed_s": round(elapsed, 2),
        }) + "\n")
        log_fh.flush()

    log_fh.close()

    # Save weights — server will pick these up on next startup (or reload).
    policy.save(_WEIGHTS_PATH)
    print(f"\nBandit weights saved → {_WEIGHTS_PATH}")
    print(f"Total updates: {policy._updates}")
    print("\nArm probabilities after training:")
    final_snap = policy.snapshot()
    # show mean weight norm per arm as a proxy for learned preference
    for arm, weights in final_snap["weights"].items():
        norm  = sum(w * w for w in weights) ** 0.5
        count = final_snap["selection_count"].get(arm, 0)
        print(f"  {arm:<20}  weight_norm={norm:.4f}  selected={count}x")

    print(f"\nPlot with: python training/plot_train_api.py")


# ── CLI ───────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="API-in-the-loop REINFORCE — LLM-only, no fake work"
    )
    parser.add_argument(
        "--base-url", default="http://localhost:8000",
        help="Environment server URL (default: http://localhost:8000)",
    )
    parser.add_argument(
        "--episodes", type=int, default=50,
        help="Number of training episodes (default: 50)",
    )
    parser.add_argument(
        "--max-steps", type=int, default=20,
        help="Max LLM steps per episode (default: 20)",
    )
    args = parser.parse_args()
    train(
        base_url=args.base_url.rstrip("/"),
        episodes=args.episodes,
        max_steps=args.max_steps,
    )
